# Labeler configuration for GitHub Actions

# ==== Feature Labels ====
"🌐 next.js":
  - apps/**/next.config.js
  - apps/**/pages/**
  - apps/**/public/**
  - apps/**/server.js
  - apps/**/middleware.js
  - apps/**/middleware.ts
  - apps/**/next-env.d.ts
  - "**/.next/**"

"⚛️ react":
  - apps/**/components/**
  - apps/**/hooks/**
  - apps/**/contexts/**
  - apps/**/pages/**
  - "**/*.tsx"

"📦 nx workspace":
  - nx.json
  - workspace.json
  - tools/**
  - project.json
  - apps/**/project.json
  - libs/**/project.json

"🛠 shared libraries":
  - libs/**
  - libs/**/index.ts
  - libs/**/src/**

"🎨 styling & UI":
  - "**/*.css"
  - "**/*.scss"
  - "**/*.less"
  - "**/*.sass"
  - "**/*.tailwind.css"

"🔧 TypeScript":
  - "**/*.ts"
  - "**/*.tsx"
  - "**/tsconfig.json"
  - "**/tsconfig.base.json"

"🗄 API & Backend":
  - apps/**/server/**
  - apps/**/api/**
  - apps/**/services/**
  - apps/**/controllers/**
  - libs/**/server/**
  - libs/**/api/**
  - libs/**/models/**

"🔌 GraphQL":
  - apps/**/graphql/**
  - libs/**/graphql/**
  - "**/*.graphql"
  - "**/*.gql"

"📊 state management":
  - apps/**/store/**
  - apps/**/redux/**
  - apps/**/context/**
  - libs/**/store/**
  - libs/**/redux/**

"🔋 caching & performance":
  - apps/**/cache/**
  - apps/**/services/cache.ts
  - "**/redis.ts"
  - "**/memcached.ts"

"🔑 authentication":
  - apps/**/auth/**
  - libs/**/auth/**
  - "**/next-auth.d.ts"
  - "**/middleware/auth.ts"
  - "**/middleware/auth.js"

"📦 dependencies":
  - package.json
  - yarn.lock
  - package-lock.json
  - pnpm-lock.yaml

"🛠️ dev dependencies":
  - package.json
  - "**/tsconfig.json"
  - "**/eslint*"
  - "**/.prettierrc"

# ==== PR Type Labels ====
"🐛 bug":
  - "**/fix/*"
  - "**/hotfix/*"
  - "**/patch/*"

"✨ enhancement":
  - "**/feature/*"
  - "**/improvement/*"

"🔥 refactor":
  - "**/refactor/*"

"🚀 new feature":
  - "**/feat/*"

"🚨 breaking change":
  - "**/breaking/*"

"♻️ chore":
  - "**/chore/*"
  - ".github/workflows/**"
  - "scripts/**"

"💡 discussion":
  - "**/discussion/**"

"🆕 version bump":
  - "version.txt"
  - ".bumpversion.cfg"

# ==== Testing Labels ====
"🧪 unit tests":
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - tests/unit/**

"📈 integration tests":
  - tests/integration/**

"🔄 e2e tests":
  - e2e/**

"🚦 CI/CD":
  - ".github/workflows/**"
  - "nx-cloud/**"
  - "pipeline/**"

# ==== Security Labels ====
"🛡️ security":
  - apps/**/security/**
  - libs/**/security/**
  - "**/*.sec.ts"

"🔒 vulnerability":
  - "**/fix/security/*"

# ==== Misc Labels ====
"🌍 localization":
  - locales/**
  - translations/**
  - "**/*.json"

"🚧 work in progress":
  - "**/wip/**"

"📌 pinned":
  - "**/pinned/**"