name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write # Needed for labeler

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Setup Node.js and cache dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      # Run affected tasks (lint, test, build, e2e)
      - run: npx nx affected -t lint test build e2e-ci
