name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for git diff

      # Determine the base branch
      - name: Determine Base Branch
        id: base_branch
        run: |
          if [ "${{ github.base_ref }}" != "" ]; then
            echo "BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
          else
            echo "BASE_BRANCH=main" >> $GITHUB_ENV
          fi

      # Fallback if base branch is missing
      - name: Ensure Base Branch Exists
        run: |
          if ! git rev-parse --verify origin/$BASE_BRANCH; then
            echo "Base branch not found, using HEAD~1 as fallback."
            echo "BASE_BRANCH=HEAD~1" >> $GITHUB_ENV
          fi

      # Debug the base branch
      - name: Debug Base Branch
        run: echo "Base branch is $BASE_BRANCH"

      # Set up Node.js environment and cache dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install Dependencies
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # Verify Nx Installation
      - name: Check Nx Installation
        run: npx nx --version

      # Run Affected Lint
      - name: Run Affected Lint
        run: npx nx affected --target=lint --parallel=3 --base=$BASE_BRANCH --head=HEAD

      # Run Affected Unit Tests
      - name: Run Affected Unit Tests
        run: npx nx affected --target=test --parallel=3 --base=$BASE_BRANCH --head=HEAD

      # Build Affected Projects
      - name: Build Affected Projects
        run: npx nx affected --target=build --parallel=3 --base=$BASE_BRANCH --head=HEAD

      # Run Affected E2E Tests
      - name: Run Affected E2E Tests
        run: npx nx affected --target=e2e --parallel=3 --base=$BASE_BRANCH --head=HEAD

      # Deploy Affected Projects to Vercel
      - name: Deploy Affected Projects to Vercel
        run: |
          affected_apps=$(npx nx affected:apps --base=$BASE_BRANCH --head=HEAD)
          for app in $affected_apps; do
            echo "Checking app: $app"
            if [[ "$app" == "sweet-sye-app" || "$app" == "nicoletta-portfolio-app" ]]; then
              echo "Deploying $app to Vercel..."
              npx vercel --cwd=apps/$app --token=$VERCEL_TOKEN --prod
            else
              echo "Skipping $app as it's not a deployable app."
            fi
          done
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # End Nx Cloud Distributed CI
      - name: Stop Nx Cloud Distributed CI
        run: npx nx-cloud stop-ci-run
